server:
    address: smtp.gmail.com
    port: 465
    user: theharrisoncrafter@gmail.com
    password: sffvijimbcqhmiqy
joke:
    url: https://icanhazdadjoke.com/
    headers:
        Accept: text/plain
        User-Agent: send_joke-py (https://gitlab.com/twh2898/send-joke)
        Accept-Charset: utf-8
mail:
    email: tharrison1@ntelos.net
    subject: Hi!, I'm Dad!
    to:
        - twh2898@vt.edu
        - rwalker19@gmail.com
